! ============================================================
!  R1 — AS65001
!  eBGP peer: R2 (AS65002) via 10.0.12.3
!  Advertises: 192.168.1.0/24
!  Security: MD5 auth, GTSM, max-prefix limit
! ============================================================
frr version 8.5
frr defaults traditional
hostname R1
log syslog informational
service integrated-vtysh-config
!
interface lo
 ip address 192.168.1.1/24
!
interface eth0
 ip address 10.0.12.2/29
 description Link-to-R2
!
ip prefix-list PL_OUT_R1 seq 5  permit 192.168.1.0/24
ip prefix-list PL_OUT_R1 seq 10 deny   0.0.0.0/0 le 32
!
ip prefix-list PL_IN_FROM_R2 seq 5  permit 192.168.2.0/24
ip prefix-list PL_IN_FROM_R2 seq 10 permit 192.168.3.0/24
ip prefix-list PL_IN_FROM_R2 seq 99 deny   0.0.0.0/0 le 32
!
bgp community-list standard COM_CUSTOMER permit 65001:100
bgp community-list standard COM_TRANSIT  permit 65001:200
!
route-map RM_EXPORT_TO_R2 permit 10
 match ip address prefix-list PL_OUT_R1
 set community 65001:100
 set local-preference 200
!
route-map RM_IMPORT_FROM_R2 permit 10
 match ip address prefix-list PL_IN_FROM_R2
 set local-preference 100
!
router bgp 65001
 bgp router-id 1.1.1.1
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 !
 neighbor 10.0.12.3 remote-as 65002
 neighbor 10.0.12.3 description R2-AS65002
 neighbor 10.0.12.3 timers 5 15
 neighbor 10.0.12.3 soft-reconfiguration inbound
 neighbor 10.0.12.3 password bgplab_secret
 neighbor 10.0.12.3 ttl-security hops 1
 !
 address-family ipv4 unicast
  network 192.168.1.0/24
  neighbor 10.0.12.3 activate
  neighbor 10.0.12.3 route-map RM_EXPORT_TO_R2 out
  neighbor 10.0.12.3 route-map RM_IMPORT_FROM_R2 in
  neighbor 10.0.12.3 send-community both
  neighbor 10.0.12.3 maximum-prefix 10 80
 exit-address-family
!
ip route 192.168.1.0/24 Null0
!
line vty
!
end
